name: Circle Permutation Benchmark

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  benchmark:
    name: Run Circle Permutation Profiling
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Get CPU Hardware Info
      run: |
        MODEL=$(lscpu | grep "Model name" | cut -d':' -f2 | xargs)
        echo "CPU_MODEL=$MODEL" >> $GITHUB_ENV

    - name: Compile Circle Algorithm
      run: |
        # Using O3 and LTO for maximum performance
        g++ -O3 -std=c++11 -march=native -flto -ffast-math -fomit-frame-pointer \
        Circle_Permutation_Algorithm.cpp -o circle_test -pthread

    - name: Execute and Capture Results
      run: |
        # Using 'tee' to ensure output is visible in logs even if the job is long
        ./circle_test | tee circle_result.txt
        
        # Parse the execution time
        TIME_VAL=$(grep "circle_test" circle_result.txt | awk '{print $3}')
        echo "TIME_CIRCLE=$TIME_VAL" >> $GITHUB_ENV

    - name: Generate Summary Report
      if: always() # Ensure report is generated even if previous steps take too long
      run: |
        echo "### 🚀 Circle Permutation Performance Report (N=14)" >> $GITHUB_STEP_SUMMARY
        echo "| Algorithm | Execution Time | Status |" >> $GITHUB_STEP_SUMMARY
        echo "| :--- | :--- | :--- |" >> $GITHUB_STEP_SUMMARY
        if [ -n "${{ env.TIME_CIRCLE }}" ]; then
          echo "| Circle Permutation | \`${{ env.TIME_CIRCLE }} s\` | Completed |" >> $GITHUB_STEP_SUMMARY
        else
          echo "| Circle Permutation | \`Running / Incomplete\` | Pending |" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "#### 💻 Runtime Environment" >> $GITHUB_STEP_SUMMARY
        echo "- **CPU Model:** ${{ env.CPU_MODEL }}" >> $GITHUB_STEP_SUMMARY
