name: Circle Permutation Benchmark

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  benchmark:
    name: Run Circle Permutation Profiling
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Get CPU Hardware Info
      run: |
        # Identify the CPU model
        MODEL=$(lscpu | grep "Model name" | cut -d':' -f2 | xargs)
        echo "CPU_MODEL=$MODEL" >> $GITHUB_ENV

    - name: Compile Circle Algorithm
      run: |
        # Use aggressive optimization flags for peak performance
        g++ -O3 -std=c++11 -march=native -flto -ffast-math -fomit-frame-pointer \
        Circle_Permutation_Algorithm.cpp -o circle_test -pthread

    - name: Execute and Capture Results
      run: |
        # Run and display output in real-time while saving to file
        ./circle_test | tee circle_result.txt
        
        # Parse the execution time from the output
        TIME_VAL=$(grep "RESULT_TIME" circle_result.txt | awk '{print $2}')
        echo "TIME_CIRCLE=$TIME_VAL" >> $GITHUB_ENV

    - name: Generate Summary Report
      run: |
        echo "### 🚀 Circle Permutation Performance Report (N=14)" >> $GITHUB_STEP_SUMMARY
        echo "| Algorithm | Execution Time | Status |" >> $GITHUB_STEP_SUMMARY
        echo "| :--- | :--- | :--- |" >> $GITHUB_STEP_SUMMARY
        echo "| Circle Permutation | \`${{ env.TIME_CIRCLE }} s\` | Completed |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "#### 💻 Runtime Environment" >> $GITHUB_STEP_SUMMARY
        echo "- **CPU Model:** ${{ env.CPU_MODEL }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Flags:** \`-O3 -march=native -flto -ffast-math\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ *Benchmark successful.*" >> $GITHUB_STEP_SUMMARY
